### ISSUE TITLE
Talk at CA2X2

### ISSUE THREAD

**Issue by CJTurpie** [UgurUysal86/MLS4MIL#1]
Hi Ugur,

I saw your talk at CA2X2 and found it really interesting, unfortunately I didn't manage to talk to you as it was the last talk of the last day and I had to go and catch a flight. You mentioned that you had just finished writing up your thesis on the work that you presented. Is this something you are able to share as I'd be really interested in your methodology and results in more detail than you were able to present.

Regards,
Carl

**Comment by UgurUysal86** [comment]
Hi Carl,

Thank you. I hope you got your flight. Everything that can be published can be found here in the repository. CA2X2 will soon release the extended abstract. Is there anything special I can help you with? 

Best regards
Ugur

**Comment by CJTurpie** [comment]
Hi Ugur,

Thanks for getting back to me. I was particularly interested in the work that you did with ML-Agents, particularly in any issues you had and how you overcame them as I'm hoping to use Unity and ML-Agents for some upcoming projects.

Regards,
Carl

**Comment by UgurUysal86** [comment]
For me, it was most convenient to work through the [ML-Agents tutorials](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Readme.md). After that, I practised using ml-agents on the [sample Unity environments](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Learning-Environment-Examples.md). After that I was ready to train agents on own models.
